name: 'SubKt Builder'
description: 'Auto-build SubKt projects'
author: 'LightArrowsEXE'

inputs:
  mux-task:
    description: 'The muxing task to execute the dependencies of. If empty, no dependency resolution will be performed'
    required: false
    default: 'mux'
  incremental:
    description: 'Only build episodes with changes (only used if mux-task is specified)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Find and Run Tasks
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x ./gradlew

        changed_dirs=$(git diff --name-only HEAD^ | grep -oE '^[0-9]+/' | sort -u | tr -d '/')

        if [ -z "$changed_dirs" ]; then
          echo "No episode directories changed"
          exit 0
        fi

        tasks_to_run=()

        for dir in $changed_dirs; do
          if ./gradlew -q tasks | grep -q "^$dir:mux\s"; then
            deps=$(./gradlew -q "$dir:mux" --dry-run | grep -oE '[0-9]+:(merge|swap|clean|chapters|qc|encode)' || true)

            if [ -n "$deps" ]; then
              tasks_to_run+=($deps)
            fi
          fi
        done

        if [ ${#tasks_to_run[@]} -eq 0 ]; then
          echo "No tasks to run"
          exit 0
        fi

        echo "Running tasks: ${tasks_to_run[*]}"
        ./gradlew "${tasks_to_run[@]}"

    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/**/*
          !build/tmp/**
          !build/.gradle/**
        if-no-files-found: error
