name: 'SubKt Builder'
description: 'Auto-build SubKt projects'
author: 'LightArrowsEXE'

inputs:
  incremental:
    description: 'Only build episodes with changes'
    required: false
    default: 'true'
  debug:
    description: 'Print debug information'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Find and Run Tasks
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x ./gradlew

        # Get list of changed files
        changed_files=$(git diff --name-only HEAD^)

        # Extract episode numbers from changed files
        episodes=$(echo "$changed_files" | grep -oE '^[0-9]+/' | sort -u | sed 's|/||')

        if [ -z "$episodes" ]; then
          echo "No episode directories changed"
          exit 0
        fi

        echo "Changed episodes: $episodes"

        # Build tasks for each episode
        tasks=()
        for ep in $episodes; do
          tasks+=("merge.$ep" "chapters.$ep" "swap.$ep")
        done

        if [ ${#tasks[@]} -eq 0 ]; then
          echo "No tasks to run"
          exit 0
        fi

        # Run all tasks
        echo "Running tasks: ${tasks[*]}"
        if [ "${{ inputs.debug }}" = "true" ]; then
          ./gradlew "${tasks[@]}" --debug
        else
          ./gradlew "${tasks[@]}"
        fi
    - name: Upload Build Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/**/*
          !build/tmp/**
          !build/.gradle/**
        if-no-files-found: error
